# Generated by Django 4.2.8 on 2023-12-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='day_of_week',
        ),
    ]
